USE codeup_test_db;
SELECT 'Pink Floyd Albums' AS 'Info';
SELECT artist, name FROM albums WHERE artist = 'Pink Floyd';
SELECT 'Release date of Sgt. Pepper''s Lonely Hearts Club Band' AS 'Info';
SELECT name, release_date FROM albums WHERE name = 'Sgt. Pepper''s Lonely Hearts Club Band';
SELECT 'Genre for the Nevermind Album' AS 'Info';
SELECT name, genre FROM albums WHERE name = 'Nevermind';
SELECT 'Albums with a release date in the 90''s' AS 'Info';
SELECT name, release_date FROM albums WHERE release_date BETWEEN 1990 AND 1999;
SELECT 'Albums whose sales were less than 20 million' AS 'Info';
SELECT name, sales FROM albums WHERE sales < 20;
SELECT 'Albums with ''rock'' as a genre' AS 'Info';
SELECT name, genre FROM albums WHERE genre = 'rock';